# Generated by Django 3.2.7 on 2021-09-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210920_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='customer',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vender',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendor'),
        ),
    ]
